### ISSUE TITLE
Add ATL-MR to Target Platform

### ISSUE THREAD

**Issue by abelgomez** [mondo-project/mondo-integration#1]
It is necessary to stabilize the code of [ATL-MR](https://github.com/atlanmod/ATL_MR) to add an update Site to the target platform.

This will allow to merge the cloudatl-unstable branch into master.

This is related with issue atlanmod/ATL_MR#5.

**Comment by agarciadom** [comment]
I've added a `thirdparty-nonp2` update site to the target platform, which is built locally from my fork. Closing for now.
